### ISSUE TITLE
Add test squares to the right of the screen too

### ISSUE THREAD

**Issue by Carl05Daniel** [MiSTer-devel/MiSTerLaggy_MiSTer#3]
I just got my Mister Laggy and I have been finding some weird stuff between all displays I have.

One particular thing I found out is that one cheap LG tv I have has less lag from the right than from the left. Could you put also white squares to the right of the display too similar to the time sleught?

**Comment by wickerwaka** [comment]
Latest release has an option to move the tests to the right hand side.

Fixed 39c7b72
